# Generated by Django 4.0.5 on 2022-06-05 00:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student_db',
            name='class_nm',
        ),
        migrations.RemoveField(
            model_name='student_db',
            name='date_nm',
        ),
    ]
